RivalsHouse_2F_Text_MayGettingReady:: @ 817337E
	.string "Το POKéMON θεραπευμένο!\n"
	.string "Τα πράγματα έτοιμα, και... Ε;$"

RivalsHouse_2F_Text_MayWhoAreYou:: @ 81733AF
	.string "Ε;\n"
	.string "Π... Ποιος είσαι;\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Ω, είσαι ο {PLAYER}{KUN}.\n"
	.string "Ώστε σήμερα ήταν η μετακόμιση.\p"
	.string "Εεε... Είμαι η MAY.\n"
	.string "Χάρηκα για τη γνωριμία!\p"
	.string "Εγώ...\n"
	.string "Εγώ έχω όνειρο να γίνω φίλη με\l"
	.string "τα POKéMON όλου του κόσμου.\p"
	.string "Ε... Έχω ακούσει για σένα, {PLAYER}{KUN},\n"
	.string "από τον μπαμπά μου, τον ΚΑΘ. BIRCH.\p"
	.string "Ήλπιζα να ήσουν καλός άνθρωπος,\n"
	.string "{PLAYER}{KUN}, και να γίνουμε φίλοι.\p"
	.string "Ω, δεν είναι κάπως γελοίο;\n"
	.string "Μ... Μόλις σε γνώρισα, {PLAYER}{KUN}.\p"
	.string "Εχεχεχε...\p"
	.string "Ωχ όχι! Ξεχάστηκα!\p"
	.string "Πρέπει να βοηθήσω τον μπαμπά να\n"
	.string "πιάσει μερικά άγρια POKéMON!\p"
	.string "{PLAYER}{KUN}, τα λέμε αργότερα!$"

RivalsHouse_2F_Text_BrendanGettingReady:: @ 81735C9
	.string "Το POKéMON θεραπευμένο!\n"
	.string "Τα πράγματα έτοιμα, και... Ε;$"

RivalsHouse_2F_Text_BrendanWhoAreYou:: @ 81735FC
	.string "Ε!\n"
	.string "Εσύ...\p"
	.string "Ποια είσαι;\p"
	.string "Ω, εσύ δεν είσαι η {PLAYER};\n"
	.string "Δίπλα μετακόμισες, σωστά;\p"
	.string "Δεν ήξερα πως είσαι κορίτσι.\p"
	.string "Ο μπαμπάς μου, ο ΚΑΘ. BIRCH, έλεγε πως\n"
	.string "είσαι παιδί του ΑΡΧΗΓΟΥ ΓΥΜΝΑΣΤΗΡΙΟΥ,\l"
	.string "και υπέθεσα πως θα ήσουν αγόρι.\p"
	.string "Με λένε BRENDAN.\n"
	.string "Γεια σου, γειτόνισσα!\p"
	.string "Ε; Πες μου, {PLAYER}, δεν έχεις\n"
	.string "POKéMON;\p"
	.string "Μήπως θες να σου πιάσω ένα;\p"
	.string "Αμάν, ξέχασα...\p"
	.string "Πρέπει να βοηθήσω τον μπαμπά να\n"
	.string "πιάσει μερικά άγρια POKéMON.\p"
	.string "Μιλάμε άλλη ώρα, εντάξει;$"

RivalsHouse_2F_Text_MayJustCheckingMyPokedex:: @ 81737AE
	.string "MAY: {PLAYER}{KUN}!\p"
	.string "Κοιτούσα τώρα στην POKéDEX μου.\p"
	.string "Υπάρχουν ακόμα πολλά POKéMON που\n"
	.string "έχω δει και δεν έχω πιάσει.\p"
	.string "Και υπάρχουν και άλλα που νομίζω\n"
	.string "πως θα εξελιχθούν.\p"
	.string "Αναρωτιέμαι πού να πάω να\n"
	.string "πιάσω POKéMON μετά...$"

RivalsHouse_2F_Text_MayWhereShouldIGoNext:: @ 8173883
	.string "Αναρωτιέμαι πού να πάω να\n"
	.string "πιάσω POKéMON μετά...\p"
	.string "Δεν θα είχε πλάκα να πέφταμε\n"
	.string "ο ένας στον άλλο, {PLAYER}{KUN};$"

RivalsHouse_2F_Text_BrendanJustCheckingMyPokedex:: @ 81738F2
	.string "BRENDAN: Α, έλα, {PLAYER}.\p"
	.string "Κοιτούσα τώρα στην POKéDEX μου.\p"
	.string "Υπάρχουν ακόμα πολλά POKéMON που\n"
	.string "πρέπει να πιάσω, αλλά μέχρι τώρα\l"
	.string "τα πηγαίνω αρκετά καλά.\p"
	.string "Μόνο που βλέπω την POKéDEX μου δίνει\n"
	.string "όρεξη να βγω πάλι στο δρόμο.$"

RivalsHouse_2F_Text_BrendanWhereShouldIGoNext:: @ 81739CC
	.string "BRENDAN: Δυσκολεύομαι να αποφασίσω\n"
	.string "πού να πάω να πιάσω POKéMON μετά.\p"
	.string "Α, {PLAYER}, αν σε πετύχω όσο θα\n"
	.string "πιάνω POKéMON, μπορούμε να κάνουμε\l"
	.string "καμιά μάχη αν θες.$"

UnknownString_8173A76: @ 8173A76
	.string "Είναι γεμάτο εικονογραφημένα βιβλία\n"
	.string "με POKéMON.$"
