LittlerootTown_BrendansHouse_1F_Text_1730C2:: @ 81730C2
LittlerootTown_MaysHouse_1F_Text_1730C2:: @ 81730C2
	.string "Ω, γεια σου. Ποι{PLAYER_ADJ_2} είσαι;\p"
	.string "... ... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ... ...\p"
	.string "Ω, είσαι {PLAYER_ART_LOWER} {PLAYER}{KUN}, {PLAYER_ART_LOWER} νέ{PLAYER_ADJ_2} μας\n"
	.string "{NEIGHBOR}! Γεια σου!\p"
	.string "Έχουμε {RIVAL_ONE} {STR_VAR_1} περίπου στην ίδια\n"
	.string "ηλικία με σένα.\p"
	.string "{RIVAL_ART} {RIVAL_CHILD} μας έλεγε πως ανυπομονεί\n"
	.string "να γνωρίσει {PLAYER_ONE} νέ{PLAYER_ADJ_2} φίλ{PLAYER_ACC}.\p"
	.string "{RIVAL_ART} {RIVAL_CHILD} μας είναι πάνω, νομίζω.$"

LittlerootTown_BrendansHouse_1F_Text_1731C6:: @ 81731C6
	.string "{RIVAL_ART} {RIVAL_CHILD} μας είναι πάνω, νομίζω.$"

LittlerootTown_BrendansHouse_1F_Text_1731E3:: @ 81731E3
	.string "Μα πού πήγε ο σύζυγός μου;\n"
	.string "Και πάνω που ήρθε {PLAYER_ART_LOWER} {PLAYER}{KUN}, κιόλας...\p"
	.string "Δεν κάθεται ποτέ στο ίδιο σημείο...\n"
	.string "Ίσως να είναι στο ΕΡΓΑΣΤΗΡΙΟ.$"

LittlerootTown_BrendansHouse_1F_Text_173262:: @ 8173262
	.string "Ω, {RIVAL_ART_LOWER} {RIVAL} έχει φύγει κάπου.\p"
	.string "Κατά μάνα, κατά κύρη...\n"
	.string "{RIVAL_ART} {RIVAL} δεν κάθεται φρόνιμα στο σπίτι.$"

LittlerootTown_BrendansHouse_1F_Text_1732B9:: @ 81732B9
	.string "Πιστεύω είναι υπέροχο ο κόσμος να\n"
	.string "ταξιδεύει με POKéMON.\p"
	.string "Αλλά καλό είναι να έρχεσαι σπίτι πού και\n"
	.string "πού για να μην ανησυχεί η μητέρα σου.\p"
	.string "Μπορεί να μην μιλάει, αλλά σίγουρα\n"
	.string "ανησυχεί για σένα, {PLAYER}{KUN}.$"
