gBirchSpeech_Welcome:: @ 81C6D78
	.string "Γεια! Συγγνώμη για την αναμονή!\p"
	.string "Καλώς ήρθες στον κόσμο των\n"
	.string "POKéMON!\p"
	.string "Το όνομά μου είναι BIRCH.\p"
	.string "Αλλά όλοι με φωνάζουν ΚΑΘΗΓΗΤΗ\n"
	.string "POKéMON.\p$"

gBirchSpeech_ThisIsPokemon:: @ 81C6DF8
	.string "Αυτό εδώ είναι που αποκαλούμε\n"
	.string "“POKéMON.”$"

gBirchSpeech_WorldInhabitedByPokemon:: @ 81C6E1A
	.string "Ο κόσμος κατοικείται ευρέως από\n"
	.string "πλάσματα γνωστά ως POKéMON.\p"
	.string "Εμείς οι άνθρωποι ζούμε μαζί με τα\n"
	.string "POKéMON, άλλοτε σαν σύντροφοι,\l"
	.string "και άλλοτε σαν συνεργάτες.\p"
	.string "Και μερικές φορές, ερχόμαστε μαζί\n"
	.string "και κάνουμε μάχες με ομοίους μας.\p"
	.string "Αλλά παρά την εγγύτητά μας, δεν\n"
	.string "ξέρουμε τα πάντα για τα POKéMON.\p"
	.string "Η αλήθεια είναι πως υπάρχουν πολλά\n"
	.string "μυστικά γύρω από τα POKéMON.\p"
	.string "Για να αποκαλύψω τα μυστήρια των\n"
	.string "POKéMON, έχω αναλάβει έρευνα.\l"
	.string "Αυτό ακριβώς κάνω.\p$"

gBirchSpeech_AndYouAre:: @ 81C6FCB
	.string "Κι εσύ ποιος είσαι;$"

gBirchSpeech_AreYouBoyOrGirl:: @ 81C6FD8
	.string "Είσαι αγόρι;\n"
	.string "Ή είσαι κορίτσι;$"

gBirchSpeech_WhatsYourName:: @ 81C6FFA
	.string "Μάλιστα.\n"
	.string "Πώς σε λένε;$"

gBirchSpeech_SoItsPlayer:: @ 81C7017
	.string "Ώστε σε λένε {PLAYER};$"

gBirchSpeech_AhOkayYouArePlayer:: @ 81C7025
	.string "Α, εντάξει!\p"
	.string "Είσαι {PLAYER_ART_LOWER} {PLAYER}, και μετακομίζεις\n"
	.string "στο LITTLEROOT, όπου και μένω.\l"
	.string "Κατάλαβα τώρα!$"

gBirchSpeech_AreYouReady:: @ 81C7074
	.string "Εντάξει, έχεις προετοιμαστεί;\p"
	.string "Η ολόδική σου περιπέτεια πρόκειται\n"
	.string "να ανοιχτεί μπροστά σου.\p"
	.string "Πάρε θάρρος, και κάνε άλμα στον\n"
	.string "κόσμο των POKéMON, όπου όνειρα,\l"
	.string "περιπέτειες, και φιλίες περιμένουν!\p"
	.string "Λοιπόν, θα σε δω αργότερα. Θα με\n"
	.string "βρεις στο ΕΡΓΑΣΤΗΡΙΟ POKéMON.\p$"
