PlayersHouse_2F_Text_ClockIsStopped:: @ 8172E18
	.string "Το ρολόι είναι σταματημένο...\p"
	.string "Ας το ρυθμίσω και να το ξεκινήσω!$"

PlayersHouse_2F_Text_HowDoYouLikeYourRoom:: @ 8172E4C
	.string "ΜΑΜΑ: {PLAYER}, πώς σου φαίνεται το\n"
	.string "νέο σου δωμάτιο;\p"
	.string "Ωραία! Όλα είναι τακτοποιημένα!\p"
	.string "Τελείωσαν και κάτω με τη\n"
	.string "μετακόμιση.\p"
	.string "Οι μεταφορείς POKéMON είναι τόσο\n"
	.string "χρήσιμοι!\p"
	.string "Ω, καλά να κάνεις να δεις αν είναι\n"
	.string "όλα τα πραγματά σου στο γραφείο.$"

UnknownString_8172F31: @ 8172F31
	.string "Η βιβλιοθήκη είναι γεμάτη βιβλία\n"
	.string "σχετικά με POKéMON.\p"
	.string "Είναι η πολύτιμη συλλογή τ{PLAYER_GEN} {PLAYER}.$"

UnknownString_8172F85: @ 8172F85
	.string "{PLAYER_ART} {PLAYER} άναψε το PC.$"

PlayersHouse_2F_Text_Notebook:: @ 8172F9A
	.string "{PLAYER_ART} {PLAYER} άνοιξε το τετράδιο.\p"
	.string "ΚΑΝΟΝΑΣ ΠΕΡΙΠΕΤΕΙΑΣ NO. 1\n"
	.string "Ανοίγεις το ΜΕΝΟΥ με το START.\p"
	.string "ΚΑΝΟΝΑΣ ΠΕΡΙΠΕΤΕΙΑΣ NO. 2\n"
	.string "Να ΑΠΟΘΗΚΕΥΕΙΣ συχνά την πρόοδό σου.\p"
	.string "Οι υπόλοιπες σελίδες είναι κενές...$"

Common_Text_LookCloserAtMap: @ 817303D
	.string "{PLAYER_ART} {PLAYER} έριξε μια καλή ματιά στον\n"
	.string "χάρτη της περιοχής HOENN.$"

PlayersHouse_2F_Text_ItsAGameCube:: @ 817306C
	.string "Είναι ένα Nintendo GameCube.\p"
	.string "Ένα Game Boy Advance είναι\n"
	.string "συνδεδεμένο σαν χειριστήριο.$"
