PlayersHouse_1F_Text_IsntItNiceInHere:: @ 8172429
	.string "ΜΑΜΑ: Βλέπεις, {PLAYER};\n"
	.string "Δεν είναι κι εδώ ωραία;$"

PlayersHouse_1F_Text_MoversPokemonGoSetClock:: @ 8172453
	.string "Τα POKéMON της μεταφορικής κάνουν\n"
	.string "όλη τη δουλειά, και μετά καθαρίζουν.\l"
	.string "Είναι τόσο βολικό!\p"
	.string "{PLAYER}, το δωμάτιό σου είναι πάνω.\n"
	.string "Ρίξε μια ματιά, αγάπη μου!\p"
	.string "Ο ΜΠΑΜΠΑΣ σου αγόρασε ένα ρολόι\n"
	.string "σαν ενθύμιο της μετακόμισής μας.\l"
	.string "Μην ξεχάσεις να το ρυθμίσεις!$"

PlayersHouse_1F_Text_ArentYouInterestedInRoom:: @ 8172531
	.string "ΜΑΜΑ: Λοιπόν, {PLAYER};\p"
	.string "Δεν σε ενδιαφέρει να δεις\n"
	.string "το δωμάτιό σου;$"

PlayersHouse_1F_Text_GoSetTheClock:: @ 8172574
	.string "ΜΑΜΑ: {PLAYER}.\p"
	.string "Πήγαινε ρύθμισε το ρολόι\n"
	.string "στο δωμάτιό σου, {HONEY} μου.$"

PlayersHouse_1F_Text_OhComeQuickly:: @ 81725A3
	.string "ΜΑΜΑ: Ω! {PLAYER}, {PLAYER}!\n"
	.string "Βιάσου! Έλα γρήγορα!$"

PlayersHouse_1F_Text_MaybeDadWillBeOn:: @ 81725C9
	.string "ΜΑΜΑ: Κοίτα! Είναι το ΓΥΜΝΑΣΤΗΡΙΟ\n"
	.string "PETALBURG! Ίσως δείξουν τον ΜΠΑΜΠΑ!$"

PlayersHouse_1F_Text_ItsOverWeMissedHim:: @ 81725FE
	.string "ΜΑΜΑ: Ω... Τελείωσε.\p"
	.string "Νομίζω έδειξαν τον μπαμπά, αλλά τον\n"
	.string "χάσαμε. Κρίμα.$"

PlayersHouse_1F_Text_GoIntroduceYourselfNextDoor:: @ 8172644
	.string "Ω, ναι.\n"
	.string "Ένας φίλος του ΜΠΑΜΠΑ μένει στην πόλη.\p"
	.string "Τον λένε ΚΑΘ. BIRCH.\p"
	.string "Μένει ακριβώς δίπλα, οπότε πήγαινε\n"
	.string "μέχρι εκεί και συστήσου.$"

PlayersHouse_1F_Text_SeeYouHoney:: @ 81726D2
	.string "ΜΑΜΑ: Τα λέμε, {HONEY} μου!$"

PlayersHouse_1F_Text_DidYouMeetProfBirch:: @ 81726E7
	.string "ΜΑΜΑ: Πήγες να συστηθείς στον\n"
	.string "ΚΑΘ. BIRCH;$"

PlayersHouse_1F_Text_YouShouldRestABit:: @ 8172717
	.string "ΜΑΜΑ: Πώς είσαι, {PLAYER};\n"
	.string "Φαίνεσαι λίγο κουρασμέν{PLAYER_ADJ}.\p"
	.string "Καλύτερα να ξεκουραστείς λιγάκι.$"

PlayersHouse_1F_Text_TakeCareHoney:: @ 817276B
	.string "ΜΑΜΑ: Να προσέχεις, {HONEY} μου!$"

PlayersHouse_1F_Text_GotDadsBadgeHeresSomethingFromMom:: @ 8172782
	.string "ΜΑΜΑ: Ω; Ο ΜΠΑΜΠΑΣ σου έδωσε αυτό το ΕΜΒΛΗΜΑ;\p"
	.string "Τότε ορίστε και κάτι από τη ΜΑΜΑ σου!$"

PlayersHouse_1F_Text_DontPushYourselfTooHard:: @ 81727CD
	.string "Μην πιέζεις τον εαυτό σου υπερβολικά,\n"
	.string "αγάπη μου. Μπορείς πάντα να έρχεσαι σπίτι.\p"
	.string "Βάλε τα δυνατά σου, {HONEY} μου!$"

PlayersHouse_1F_Text_Machoke1:: @ 817281D
	.string "Γκιάο, γκιάο, γκιάο...$"

PlayersHouse_1F_Text_Machoke2:: @ 8172831
	.string "Γκουαγκουά γκουά...$"

PlayersHouse_1F_Text_ReportFromPetalburgGym:: @ 8172841
	.string "ΔΗΜΟΣΙΟΓΡΑΦΟΣ: ...Σας φέραμε αυτό το\n"
	.string "ρεπορτάζ από το ΓΥΜΝ. PETALBURG.$"

PlayersHouse_1F_Text_TheresAMovieOnTV: @ 817288C
	.string "Παίζει μια ταινία στην τηλεόραση.\p"
	.string "Δύο άντρες χορεύουν πάνω σε ένα\n"
	.string "τεράστιο πιάνο.\p"
	.string "Καλύτερα να πηγαίνω!$"

UnknownString_81728E3: @ 81728E3
	.string "Είναι το εγχειρίδιο για τα\n"
	.string "ΑΘΛΗΤΙΚΑ ΠΑΠΟΥΤΣΙΑ.\p"
	.string "“Πίεσε το Πλήκτρο B για να τρέξεις\n"
	.string "ενώ φοράς τα ΑΘΛΗΤΙΚΑ ΠΑΠΟΥΤΣΙΑ.\p"
	.string "“Δέσε τα ΑΘΛΗΤΙΚΑ ΠΑΠΟΥΤΣΙΑ και\n"
	.string "πάρε το δρόμο τρέχοντας!”$"

PlayersHouse_1F_Text_TicketFromBrineyCameForYou:: @ 817298B
	.string "ΜΠΑΜΠΑΣ: Χμ;\p"
	.string "Ω, είναι {PLAYER_ART_LOWER} {PLAYER}!\p"
	.string "Έχω πολύ καιρό να σε δω, αλλά μου\n"
	.string "φαίνεσαι...δυνατότερ{PLAYER_ADJ}, κάπως.\p"
	.string "Αυτή την εντύπωση μου δίνεις.\n"
	.string "Αλλά δεν τα παρατά ακόμα ο γέρος σου!\p"
	.string "Α, ναι, έχω κάτι εδώ για σένα.\n"
	.string "Αυτό ήρθε από κάποιον που λέγεται\l"
	.string "ΚΟΣ. BRINEY.$"

PlayersHouse_1F_Text_PortsInSlateportLilycove:: @ 8172A7D
	.string "ΜΠΑΜΠΑΣ: Χμ, ένα ΕΙΣΙΤΗΡΙΟ για φέρι μποτ;\p"
	.string "Αν θυμάμαι σωστά, υπάρχει λιμάνι\n"
	.string "στη SLATEPORT και στη LILYCOVE."
	.string "{PLAYER}, αν έχεις προσδοκίες ως\n"
	.string "{TRAINER}, πήγαινε στον ΠΥΡΓΟ ΜΑΧΗΣ.\p"
	.string "Θα σου μάθει πως δεν υπάρχει τέλος\n"
	.string "στο δρόμο που διαλέγει ένας ΕΚΠΑΙΔΕΥΤΗΣ.$"

PlayersHouse_1F_Text_BetterGetBackToGym:: @ 8172B5E
	.string "Καλύτερα να πηγαίνω πίσω στο\n"
    .string	"ΓΥΜΝΑΣΤΗΡΙΟ PETALBURG.\p"
	.string "ΜΑΜΑ, σ' ευχαριστώ που προσέχεις\n"
	.string "το σπίτι όσο λείπω.$"

PlayersHouse_1F_Text_DadShouldStayLonger:: @ 8172BBC
	.string "ΜΑΜΑ: Αυτός ο ΜΠΑΜΠΑΣ σου...\p"
	.string "Έρχεται σπίτι για πρώτη φορά εδώ και\n"
	.string "καιρό, και μόνο για POKéMON μιλάει.\p"
	.string "Πρέπει να χαλαρώσει και να μείνει\n"
	.string "σπίτι για λιγάκι.$"

UnknownString_8172C50: @ 8172C50
	.string "Διακόπτουμε το πρόγραμμά μας για\n"
	.string "μία έκτακτη είδηση!\p"
	.string "Υπάρχουν αναφορές ενός μπλε ΙΠΤΑΜΕΝΟΥ\n"
	.string "POKéMON σε διάφορα τοπία της HOENN.\p"
	.string "Η ταυτότητα του POKéMON είναι\n"
	.string "αυτή τη στιγμή άγνωστη.\p"
	.string "Επιστρέφουμε τώρα στο\n"
	.string "κανονικό μας πρόγραμμα..$"

UnknownString_8172D30: @ 8172D30
	.string "Διακόπτουμε το πρόγραμμά μας για\n"
	.string "μία έκτακτη είδηση!\p"
	.string "Υπάρχουν αναφορές ενός κόκκινου ΙΠΤΑΜΕΝΟΥ\n"
	.string "POKéMON σε διάφορα τοπία της HOENN.\p"
	.string "Η ταυτότητα του POKéMON είναι\n"
	.string "αυτή τη στιγμή άγνωστη.\p"
	.string "Επιστρέφουμε τώρα στο\n"
	.string "κανονικό μας πρόγραμμα..$"

UnknownString_8172E0F: @ 8172E0F
	.string "Γκάου γκάου!$"
