LittlerootTown_Text_16A7C9:: @ 816A7C9
	.string "MOM: {PLAYER}, φτάσαμε, {HONEY} μου!\p"
	.string "Θα είσαι κουρασμέν{PLAYER_ADJ} μετά το ταξίδι\n"
	.string "μέσα στο φορτηγό της μεταφορικής.\p"
	.string "Λοιπόν, αυτή είναι η ΠΟΛΗ LITTLEROOT.\p"
	.string "Πως σου φαίνεται;\n"
	.string "Αυτό είναι το νέο μας σπίτι!\p"
	.string "Έχει γραφική ατμόσφαιρα, αλλά\n"
	.string "φαίνεται πολύ άνετο μέρος. Τι νομίζεις;\p"
	.string "Και έχεις και δικό σου δωμάτιο,\n"
	.string "{PLAYER}! Ας μπούμε μέσα.$"

LittlerootTown_Text_16A8EE:: @ 816A8EE
	.string "ΜΑΜΑ: Περίμενε, {PLAYER}!$"

LittlerootTown_Text_16A8FD:: @ 816A8FD
	.string "ΜΑΜΑ: {PLAYER}! {PLAYER}!\n"
	.string "Συστήθηκες στον ΚΑΘ. BIRCH;\p"
	.string "Ω! Μα τι χαριτωμένο POKéMON!\n"
	.string "Το πήρες από τον ΚΑΘ. BIRCH. Τι ωραία!\p"
	.string "Είσαι όντως του πατέρα σου παιδί.\n"
	.string "Φαίνεσαι καλά μαζί με το POKéMON!\p"
	.string "Ορίστε, {HONEY} μου! Αν είναι να φύγεις,\n"
	.string "φόρα αυτά τα ΑΘΛΗΤΙΚΑ ΠΑΠΟΥΤΣΙΑ.\p"
	.string "Θα πηγαίνεις παντού σε χρόνο μηδέν!$"

LittlerootTown_Text_16AA32:: @ 816AA32
	.string "{PLAYER_ART} {PLAYER} φόρεσε τα\n"
	.string "ΑΘΛΗΤΙΚΑ ΠΑΠΟΥΤΣΙΑ.$"

LittlerootTown_Text_16AA5C:: @ 816AA5C
	.string "ΜΑΜΑ: {PLAYER}, αυτά τα παπούτσια\n"
	.string "ήρθαν με οδηγίες.\p"
	.string "“Πίεσε το Πλήκτρο B ενώ φοράς αυτά τα\n"
	.string "ΠΑΠΟΥΤΣΙΑ για να τρέξεις γρήγορα!\p"
	.string "“Φόρεσε αμέσως αυτά τα ΑΘΛΗΤΙΚΑ\n"
	.string "ΠΑΠΟΥΤΣΙΑ, και τρέξε προς την εξοχή!”$"

LittlerootTown_Text_16AB10:: @ 816AB10
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Το ότι έχεις δικό σου\n"
	.string "POKéMON τώρα...\l"
	.string "Ο πατέρας σου θα καταχαρεί.\p"
	.string "…Αλλά να προσέχεις, σε παρακαλώ.\n"
	.string "Αν συμβεί το οτιδήποτε, γύρνα σπίτι.\p"
	.string "Εμπρός, βάλε τα δυνατά σου, {HONEY} μου!$"

LittlerootTown_Text_16AC00:: @ 816AC00
	.string "Αν χρησιμοποιήσεις PC, μπορείς να\n"
	.string "αποθηκεύεις αντικείμενα και POKéMON.\p"
	.string "Η δύναμη της επιστήμης είναι\n"
	.string "συγκλονιστική!$"

LittlerootTown_Text_16AC56:: @ 816AC56
	.string "Ο ΚΑΘ. BIRCH αφιερώνει μέρες στο\n"
	.string "ΕΡΓΑΣΤΗΡΙΟ μελετώντας,\p"
	.string "και μετά βγαίνει ξαφνικά έξω\n"
	.string "στη φύση να κάνει έρευνα...\p"
	.string "Περνάει ποτέ ο ΚΑΘ. BIRCH χρόνο\n"
	.string "στο σπίτι του;$"

LittlerootTown_Text_16ACEB:: @ 816ACEB
	.string "Αν μπεις στο ψηλό γρασίδι στη μέση του\n"
	.string "δρόμου, θα εμφανιστούν άγρια POKéMON.$"

LittlerootTown_Text_16AD3C:: @ 816AD3C
	.string "Δεν είναι ασφαλές εκεί έξω αν δεν\n"
	.string "έχεις κανένα POKéMON μαζί σου.$"

LittlerootTown_Text_16AD82:: @ 816AD82
	.string "Ακούω κάποιον να φωνάζει πιο πέρα\n"
	.string "στο δρόμο.\p"
	.string "Τι να κάνω; Τι να κάνω;\n"
	.string "Κάποιος πρέπει να βοηθήσει...$"

LittlerootTown_Text_16ADF2:: @ 816ADF2
	.string "Χαίρομαι πολύ που πήγες και έσωσες\n"
	.string "τον ΚΑΘΗΓΗΤΗ.$"

LittlerootTown_Text_16AE25:: @ 816AE25
	.string "Θα πας να πιάσεις POKéMON;\n"
	.string "Καλή επιτυχία!$"

LittlerootTown_Text_16AE50:: @ 816AE50
	.string "ΠΟΛΗ LITTLEROOT\n"
	.string "“Μια πόλη δίχως καμία απόχρωση.”$"

LittlerootTown_Text_16AE87:: @ 816AE87
	.string "ΕΡΓΑΣΤΗΡΙΟ POKéMON ΚΑΘ. BIRCH$"

LittlerootTown_Text_16AEA1:: @ 816AEA1
	.string "ΣΠΙΤΙ Τ{PLAYER_GEN_CAP} {PLAYER}$"

LittlerootTown_Text_16AEAC:: @ 816AEAC
	.string "ΣΠΙΤΙ ΤΟΥ ΚΑΘ. BIRCH$"
